declare global {
  namespace Twitch {
    namespace jwt {
      interface TransactionPayload {
        /**
         * Indicates the type of receipt. Valid value: `bits_transaction_receipt`.
         */
        topic: 'bits_transaction_receipt'
        /**
         * Unix timestamp when this receipt expires.
         */
        exp: number
        /**
         * Container for receipt payload data.
         */
        data: {
          /**
           * ID of the transaction.
           */
          transactionId: string
          /**
           * UTC timestamp when this transaction occurred.
           */
          time: string
          /**
           * Twitch ID of the user who executed the transaction.
           */
          userId: string
          product: {
            /**
             * Will be `twitch.ext` + your extension ID.
             */
            domainId: string
            /**
             * Unique ID for the product.
             */
            sku: string
            /**
             * Registered display name for the SKU.
             */
            displayName: string
            /**
             * Cost object.
             */
            cost: {
              /**
               * Number of Bits required for the product.
               */
              amount: number
              /**
               * Always the string `bits`. Reserved for future use.
               */
              type: 'bits'
            }
          }
        }
      }

      interface ExtensionPayload {
        /**
         * Expiration time for the JWT, expressed as seconds since Jan 1, 1970. (For a definition of NumericDate, see [Terminology](https://tools.ietf.org/html/rfc7519#section-2) in the JWT RFC.)
         */
        exp: number
        /**
         * Identifies the session using this JWT. Any token generated by your EBS should leave this field blank. When present, the value is interpreted as follows:
         *
         * - Values beginning with "U" are stable references to a Twitch account across sessions and channels. You can use them to provide persistent services to users.
         * - Values beginning with "A" are transient references to an anonymous Twitch session; the user has not logged into the Twitch website. These values are not stable and should never be associated with persistent data. It is possible for them to represent different users over time. If your extension requires a stable user identity, your front-end interface should display an appropriate login request when this field does not begin with "U."
         *
         * Broadcasters' tokens are set with "U" + their Twitch user IDs, to avoid confusing opaque IDs with user IDs when the broadcaster is a viewer.
         */
        opaque_user_id: string
        /**
         * The user's Twitch user ID. This is provided only for users who allow your extension to identify them. There are no guarantees this will be available, as users can revoke an extension's ability to identify them at any time. Users who revoke an extension's ability to identify them are issued a new opaque identifier.
         */
        user_id: string
        /**
         * Numeric ID of the channel from which your front-end is being served.
         */
        channel_id: string
        /**
         * Type of user for whom this JWT has been signed. This is required. Valid values:
         *
         * - `broadcaster` — The owner of the channel, who should have configuration rights.
         * - `moderator` — A viewer who has moderation rights on the channel. This is provided only for users who allow your extension to identify them.
         * - `viewer` — A user watching the channel.
         * - `external` — The token is not from a Twitch token generator. Your EBS should use this value to generate tokens when it broadcasts messages. Multiple endpoints require this role.
         */
        role: 'broadcaster' | 'moderator' | 'viewer' | 'external'
        /**
         * `true` when the token is for a user that previously shared identity; otherwise, `false`.
         */
        is_unlinked: boolean
        /**
         * Defines the ability of the token holder to send and listen to messages for your extension. `pubsub_perms` contains two arrays: `listen` and `send`, which contain the topics the associated user is allowed to listen to and publish to, respectively.
         *
         * A wildcard/asterisk means the associated user can listen/publish to all topics associated with that extension/channel combination. A list of specific values means only the specified targets are allowed. If a permission is absent, it is equivalent to the empty listing: there are no default allowed targets. When sending messages from the EBS, specify an asterisk as the `send` permission, to allow the message to pass through the system.
         */
        pubsub_perms: {
          listen: string[]
          send: string[]
        }
      }
    }
  }
}

export {}
